name: Project Building
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-dotnet@main

      - name: Cache
        uses: actions/cache@main
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Building
        run: dotnet build -c ${{ matrix.configuration }}

      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.configuration }}
          path: |
            **/bin/**/*.nupkg