name: Project Building
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/cache@main
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: nuget-${{ runner.os }}-
      - run: dotnet build -c ${{ matrix.configuration }}
      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.configuration }}
          path: '**/bin/**/*.nupkg'