name: Project Publishing
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/cache@main
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: nuget-${{ runner.os }}-
      - run: dotnet build -c Release
      - run: |
          nuget sources add -name github -Source https://nuget.pkg.github.com/lindexi/index.json -Username Qusay -Password ${{ secrets.QUSAY_TOKEN }}
          nuget push .\bin\Release\*.nupkg -Source github -SkipDuplicate
          nuget push .\bin\Release\*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NUGETKEY }} 
